name: CatacombsGame
version: '${version}'
main: ru.vikhrenko.catacombsGame.CatacombsGame
api-version: '26.1.2'

dependencies:
  server:
    CatacombsGenerator:
      required: true
      load: BEFORE

    MinigameService:
      required: true
      load: BEFORE

    ServerUtils:
      required: true
      load: BEFORE
